---
abstract: 'Alternate Module Implementations'
author:
  - 'Ingy döt Net <ingy@ingy.net>'
build_requires:
  Test::Exception: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Alt
no_index:
  directory:
    - inc
    - t
    - xt
    - example
requires:
  perl: v5.8.1
resources:
  bugtracker: https://github.com/ingydotnet/alt-pm/issues
  homepage: https://github.com/ingydotnet/alt-pm
  repository: https://github.com/ingydotnet/alt-pm.git
version: '0.08'
