---
abstract: 'Alternate Module Implementations'
author:
  - 'Ingy döt Net <ingy@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Alt
name: Alt
no_index:
  directory:
    - inc
    - t
resources:
  homepage: https://github.com/ingydotnet/alt-pm/tree
  license: http://opensource.org/licenses/artistic-license.php
  repository:
    type: git
    url: git://github.com/ingydotnet/alt-pm.git
    web: https://github.com/ingydotnet/alt-pm/tree
version: 0.03
